#version: "3.8"

services:
  cog-tile-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: cog-tile-server:latest
    container_name: cog-tile-server
    ports:
      - "8000:8000"
    environment:
      # You can tune these at runtime without rebuilding
      GDAL_CACHEMAX: "1024"
      GDAL_NUM_THREADS: "ALL_CPUS"
      GDAL_TIFF_OVR_BLOCKSIZE: "128"
      PYTHONUNBUFFERED: "1"
    volumes:
      # Persist generated COGs across restarts
      - ./cache:/app/cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s